### ISSUE TITLE
kdl_parser headers installed to incorrect path

### ISSUE THREAD

**Issue by daniel-dsouza** [ros/kdl_parser#77] opened 2023-09-21 23:24 UTC
### Steps to reproduce:

1. Install `ros-humble-kdl-parser` package
2. (optional) clone humble branch and build

### What went wrong:

Headers are installed in `/opt/ros/humble/include/kdl_parser/kdl_parser`. To include these files, you would need to include

`<kdl_parser/kdl_parser/kdl_parser.hpp>`

However `kdl_parser.hpp` cannot find `<kdl_parser/visibility_control.hpp>`.

### Expected behavior:

Code should include kdl_parser with `kdl_parser/kdl_parser.hpp`

### Workaround

Fix CMakeLists.txt to install headers in the correct directory per the following documentation.
https://docs.ros.org/en/foxy/How-To-Guides/Ament-CMake-Documentation.html#building-a-library

**Comment by clalancette** [comment] 2023-09-27 17:12
This is expected behavior; since Galactic we install everything to an extra `include` directory.  However, the CMake variables that downstream packages use should do the right thing so that you only have to do `#include <kdl_parser/kdl_parser.hpp>`.

Because this is a feature and not a bug, I'm going to close this one out.  But please feel free to keep commenting.

**Closed as not planned by clalancette** 2023-09-27 17:12 UTC
